### ISSUE TITLE
make install fails

### ISSUE THREAD

**Issue by OliverSchmitz** [pcraster/lue#111]
[100%] Built target lue_validate
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /tmp/lue_install/./include
-- Up-to-date: /tmp/lue_install/./include/lue
-- Up-to-date: /tmp/lue_install/./include/lue/configure.hpp
-- Up-to-date: /tmp/lue_install/lib/cmake/lue/lue_targets.cmake
-- Installing: /tmp/lue_install/lib/cmake/lue/lue_targets-release.cmake
CMake Error at source/cmake_install.cmake:64 (file):
  file INSTALL cannot find
  "/home/foo/development/projects/lue/source/lue-config.cmake".
Call Stack (most recent call first):
  cmake_install.cmake:48 (include)

**Comment by kordejong** [comment]
Can you show me how you configured the project (LUE_BUILD_XXX stuff)?

**Comment by OliverSchmitz** [comment]
cmake -DCMAKE_INSTALL_PREFIX=/tmp/lue_install -DLUE_BUILD_ALL:BOOL=TRUE -DLUE_BUILD_PYTHON_API:BOOL=TRUE -DLUE_BUILD_TEST:BOOL=TRUE -DLUE_BUILD_DOCUMENTATION:BOOL=TRUE ~/development/projects/lue
