### ISSUE TITLE
Please add a configure flag to set the installation directory of Python files

### ISSUE THREAD

**Issue by OliverSchmitz** [pcraster/lue#189]
This is desired as Conda doesn't like moving files around in a post-install step

**Comment by kordejong** [comment]
Can you please provide the envisioned cmake call to set this flag? Is there some convention for doing this, used by other packages?

**Comment by OliverSchmitz** [comment]
For PCRaster I slammed this in due to time restrictions, by -DPCRASTER_PYTHON_INSTALL_DIR= or using our default python directory. CMake now also has a Python_SITELIB that could be used.
I'll check if there is a more solid approach and propose it. This is more a mid-term request, as for our channel we can use the copying approach fttb.

**Comment by kordejong** [comment]
The install path of LUE's Python APIs can be set using a new configuration variable called LUE_PYTHON_API_INSTALL_DIR. By default it is set to a subdirectory called `lue` in the current Python's site packages location. Does this work for you?

Closing the issue. You can reopen it if necessary.
