### ISSUE TITLE
CMake configure step fails when lue_view requested

### ISSUE THREAD

**Issue by OliverSchmitz** [pcraster/lue#242]
LUE configure options are

-D LUE_DATA_MODEL_WITH_PYTHON_API=ON \
-D LUE_DATA_MODEL_WITH_UTILITIES=ON \
-D LUE_BUILD_VIEW=ON \

 cmake configure step fails due to imgui::imgui target not found
with LUE_BUILD_VIEW=OFF cmake succeeds

**Comment by kordejong** [comment]
Should work now, with `-DLUE_BUILD_VIEW=ON`. LUE knows how to build imgui, but this logic was not selected due to a bug in the CMake scripts.
